/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMintMapInterface extends ethers.utils.Interface {
  functions: {
    "decMintMapValue(uint256,address,uint256)": FunctionFragment;
    "getMintMapValue(uint256,address)": FunctionFragment;
    "incMintMapValue(uint256,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "decMintMapValue",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMintMapValue",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "incMintMapValue",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "decMintMapValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintMapValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incMintMapValue",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMintMap extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMintMapInterface;

  functions: {
    decMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "decMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getMintMapValue(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getMintMapValue(uint256,address)"(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    incMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "incMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  decMintMapValue(
    id: BigNumberish,
    account: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "decMintMapValue(uint256,address,uint256)"(
    id: BigNumberish,
    account: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getMintMapValue(
    id: BigNumberish,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getMintMapValue(uint256,address)"(
    id: BigNumberish,
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  incMintMapValue(
    id: BigNumberish,
    account: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "incMintMapValue(uint256,address,uint256)"(
    id: BigNumberish,
    account: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    decMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "decMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getMintMapValue(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMintMapValue(uint256,address)"(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "incMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    decMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "decMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getMintMapValue(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMintMapValue(uint256,address)"(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    incMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "incMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    decMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "decMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getMintMapValue(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMintMapValue(uint256,address)"(
      id: BigNumberish,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    incMintMapValue(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "incMintMapValue(uint256,address,uint256)"(
      id: BigNumberish,
      account: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
