/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ITokenForgeInterface extends ethers.utils.Interface {
  functions: {
    "forgeItem(uint256,address,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "forgeItem",
    values: [BigNumberish, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "forgeItem", data: BytesLike): Result;

  events: {};
}

export class ITokenForge extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ITokenForgeInterface;

  functions: {
    forgeItem(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "forgeItem(uint256,address,uint256,uint256,uint256)"(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  forgeItem(
    forgingDiffId: BigNumberish,
    forgee: string,
    hashVal: BigNumberish,
    value: BigNumberish,
    forgedAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "forgeItem(uint256,address,uint256,uint256,uint256)"(
    forgingDiffId: BigNumberish,
    forgee: string,
    hashVal: BigNumberish,
    value: BigNumberish,
    forgedAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    forgeItem(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "forgeItem(uint256,address,uint256,uint256,uint256)"(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    forgeItem(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "forgeItem(uint256,address,uint256,uint256,uint256)"(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    forgeItem(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "forgeItem(uint256,address,uint256,uint256,uint256)"(
      forgingDiffId: BigNumberish,
      forgee: string,
      hashVal: BigNumberish,
      value: BigNumberish,
      forgedAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
