/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITokenPriceProvider } from "../ITokenPriceProvider";

export class ITokenPriceProvider__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenPriceProvider {
    return new Contract(address, _abi, signerOrProvider) as ITokenPriceProvider;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getTokenEthPrice",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
