/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITokenForge } from "../ITokenForge";

export class ITokenForge__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenForge {
    return new Contract(address, _abi, signerOrProvider) as ITokenForge;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "forgingDiffId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "forgee",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "hashVal",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "forgedAmount",
        type: "uint256",
      },
    ],
    name: "forgeItem",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
